### ISSUE TITLE
signature error on 19.07.3?

### ISSUE THREAD

**Issue by youxiaojie** [openwrt-dev/feeds#5]
Downloading https://github.com/openwrt-dev/feeds/raw/ramips-mt7620/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_dev_base
Downloading https://github.com/openwrt-dev/feeds/raw/ramips-mt7620/base/Packages.sig
Signature check failed.
Remove wrong Signature file.

**Comment by pexcn** [comment]
Try this:
```bash
cd /tmp
wget https://raw.githubusercontent.com/openwrt-dev/feeds/master/key-build.pub
opkg-key add key-build.pub

opkg update
```

**Comment by youxiaojie** [comment]
dear friend, if I want to build image to integrate these packages into image(not as module)  how to add this feed? to edit feeds.conf.default? and then scripts/feeds update -a /scripts/feeds install -a?

**Comment by pexcn** [comment]
Maybe, you can try it, I don't know much about openwrt.
